### PR TITLE
Improve ux with clean navigation and better a11y

### PR DESCRIPTION
**Pull request by manuelmeister**
I tried to improve on the current design. I also improved the accessibility of the navigation and forms.

Feature Deployment: https://manuelmeister.github.io/hering/

**Improved navigation on mac:**
|before|after|
|-|-|
|Bildschirmfoto 2024-04-11 um 22 32 14|Bildschirmfoto 2024-04-11 um 22 33 14|

**Improved calendar:** https://manuelmeister.github.io/hering/#/calendar
|before|after|
|-|-|
|Bildschirmfoto 2024-04-11 um 22 34 20|Bildschirmfoto 2024-04-11 um 22 34 07|

### CODE REVIEW

**Comment by manuelmeister** [comment]
@ewangler kannst du mal ein feature deployment machen?

**Comment by manuelmeister** [comment]
@mario-zelger can you have a look? 😊

**Comment by mario-zelger** [comment]
Very nice, thank you! Will check it out tomorrow and most likely merge right away 👍

**Comment by ewangler** [comment]
@manuelmeister very very cool! thanks a lot! 🎉  i love the fish 🐟 

there is just one small thing that i'm not 100% sure about: in the calendar you changed the link to the chapter to "Kapitel". i get that and it's better because it's shorter, but maybe it's also not that clear for a user. maybe there is an other label like "Zum Kapitel" or "Mehr Infos"...

**Comment by mario-zelger** [comment]
I manually merged the pull request on my side because I realized that I forgot to push one commit before the fall courses. Of course there were some conflicts 🤦‍♂️.

Unfortunately, GitHub does not seem to have recognized that merge here. Therefore, I would close this one without an explict merge via GH.

@manuelmeister Can you check out the current develop branch? All of your changes should be there.

**Comment by manuelmeister** [comment]
Strange

**Comment by manuelmeister** [comment]
@mario-zelger don't forget to deploy

**Comment by mario-zelger** [comment]
all done 👍

**Pull request closed without merging**
